apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab-director.fullname" . }}-backend
  labels:
    {{- include "lab-director.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lab-director.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
