apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lab-director.fullname" . }}
  labels:
    {{- include "lab-director.labels" . | nindent 4 }}
data:
  OPERATOR_URL: {{ .Values.backend.env.OPERATOR_URL | quote }}
  {{- if .Values.backend.env.TEMPORAL_HOST_PORT }}
  TEMPORAL_HOST_PORT: {{ .Values.backend.env.TEMPORAL_HOST_PORT | quote }}
  {{- end }}
  {{- if .Values.backend.env.TEMPORAL_NAMESPACE }}
  TEMPORAL_NAMESPACE: {{ .Values.backend.env.TEMPORAL_NAMESPACE | quote }}
  {{- end }}
  {{- if .Values.backend.env.LITELLM_URL }}
  LITELLM_URL: {{ .Values.backend.env.LITELLM_URL | quote }}
  {{- end }}
