{{- if .Values.worker.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.worker.serviceAccountName }}
  labels:
    {{- include "lab-director.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}
