apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dev-environment.fullname" . }}-workspace
  labels:
    {{- include "dev-environment.labels" . | nindent 4 }}
    reynoza.co/ticket-id: {{ .Values.ticket.id | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.workspace.storageClass }}
  resources:
    requests:
      storage: {{ .Values.workspace.storageSize }}
