apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium-system
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: ">0.0.0"         # pin later if you wish
      helm:
        releaseName: cilium
        valueFiles:
          - "$values/helm/cilium-values.yaml"
    - repoURL: git@github.com:aaronreynoza/homelab.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
