apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  source:
    repoURL: git@github.com:aaronreynoza/homelab.git
    targetRevision: main
    path: apps/ns-longhorn
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
