apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "sandbox.fullname" . }}-limits
  labels:
    {{- include "sandbox.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      max:
        cpu: {{ .Values.limitRange.maxCpu | quote }}
        memory: {{ .Values.limitRange.maxMemory }}
      default:
        cpu: {{ .Values.limitRange.defaultCpu | quote }}
        memory: {{ .Values.limitRange.defaultMemory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu | quote }}
        memory: {{ .Values.limitRange.defaultRequestMemory }}
