apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs-site
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aaronreynoza/homelab.git
    targetRevision: main
    path: core/manifests/apps/docs-site
  destination:
    server: https://kubernetes.default.svc
    namespace: docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
