apiVersion: v1
kind: Namespace
metadata:
  name: forgejo-runner
  labels:
    app.kubernetes.io/managed-by: argocd
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
