apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-docker-data
  namespace: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
