apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
spec:
  provider:
    kubernetes:
      # ESO reads source secrets from the "secrets" namespace
      remoteNamespace: secrets
      server:
        # Same cluster
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-system
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-store-reader
          namespace: external-secrets
