apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-aaron-reynoza-org
  namespace: cert-manager
spec:
  secretName: wildcard-aaron-reynoza-org-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "aaron.reynoza.org"
    - "*.aaron.reynoza.org"
  renewBefore: 720h
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cilium-system,cilium-secrets,argocd,forgejo,harbor,monitoring,zitadel,ai,management"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "cilium-system,cilium-secrets,argocd,forgejo,harbor,monitoring,zitadel,ai,management"
