name: Packer - Talos template (Proxmox)

on:
  workflow_dispatch: {}
  push:
    paths:
      - "packer/talos-packer/**"
      - ".github/workflows/packer-build.yml"

jobs:
  build:
    runs-on: [self-hosted, linux, x64, proxmox]
    env:
      PROXMOX_API_URL: ${{ secrets.PROXMOX_API_URL }}
      PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
      PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET }}
      PROXMOX_NODE: ${{ secrets.PROXMOX_NODE }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Packer init
        run: packer init packer/talos-packer

      - name: Packer validate
        run: |
          packer validate \
            -var "proxmox_api_url=${PROXMOX_API_URL}" \
            -var "proxmox_api_token_id=${PROXMOX_TOKEN_ID}" \
            -var "proxmox_api_token_secret=${PROXMOX_TOKEN_SECRET}" \
            -var "proxmox_node=${PROXMOX_NODE}" \
            -var-file packer/talos-packer/vars/local.pkrvars.hcl \
            packer/talos-packer

      - name: Packer build
        run: |
          packer build \
            -var "proxmox_api_url=${PROXMOX_API_URL}" \
            -var "proxmox_api_token_id=${PROXMOX_TOKEN_ID}" \
            -var "proxmox_api_token_secret=${PROXMOX_TOKEN_SECRET}" \
            -var "proxmox_node=${PROXMOX_NODE}" \
            -var-file packer/talos-packer/vars/local.pkrvars.hcl \
            packer/talos-packer
